### ISSUE TITLE
provide a list of task ids to commands

### ISSUE THREAD

**Issue by zumbie** [nonce9/godo#1]
It happens that I finish several tasks at once. Therefore it would be nice to toggle their status with one command invocation.

A list could look like this:
godo toggle 2,3-6,8
or just
godo toggle 0 1 10 300

It might benefit delete too.

**Comment by nonce9** [comment]
Passing a list of task ids to the `toggle` and `delete` command is now possible with the latest release (0.7.0).

Since opening the issue, the `toggle` command has become a subcommand of the `task` command. So to provide an example, the following would toggle 3 tasks with the ids 6,7 and 10:

```
godo task toggle 6 7 10
```
